using System.Runtime.CompilerServices;
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

[assembly: InternalsVisibleTo("Assembly-CSharp.Tests")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Explorables")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Tests1")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Tests2")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Tests3")]
[assembly: InternalsVisibleTo("Aprende.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego1.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego1.Tests1")]
[assembly: InternalsVisibleTo("ManejoJuego2.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego3.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego4.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego5.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego6.Tests")]
[assembly: InternalsVisibleTo("ManejoJuego7.Tests")]
[assembly: InternalsVisibleTo("PreguntasDBNoveno.Tests")]
